version: "3.8"
services:
  langexchange:
    image: langexchange
    build:
      dockerfile: Dockerfile
    container_name: langexchange
    volumes:
      - .:/langexchange
      - node_modules:/langexchange/node_modules/
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
volumes:
  node_modules:
